"""
Django settings for portfolio_project project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""


# settings.py
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


import environ  # Make sure to install python-environ

# Initialize environment variables
env = environ.Env()
environ.Env.read_env()

# Redis Configuration
REDIS_URL = env('REDIS_URL', default='redis://localhost:6379')

# Channel Layers Configuration
CHANNEL_LAYERS = {
    ''' "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [REDIS_URL],
            "symmetric_encryption_keys": [env('ENCRYPTION_KEY', default='secret-key-here')],
        },
    },'''
    
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },

}

# Optional: Direct Redis connection configuration if needed elsewhere
REDIS_CONNECTION = {
    'URL': REDIS_URL,
    'MAX_CONNECTIONS': env.int('REDIS_MAX_CONNECTIONS', default=100),
    'TIMEOUT': env.int('REDIS_TIMEOUT', default=30),
}

# settings.py (additional config)
# For production environments only
'''
if not DEBUG:
    CHANNEL_LAYERS["default"]["CONFIG"].update({
        "connection_pool": redis.ConnectionPool.from_url(
            REDIS_URL,
            max_connections=REDIS_CONNECTION['MAX_CONNECTIONS'],
            socket_timeout=REDIS_CONNECTION['TIMEOUT']
        )
    }
    '''

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# Helper to read boolean env vars ("1", "true", "yes" -> True).
def _env_bool(name: str, default: bool = False) -> bool:
    raw = os.environ.get(name)
    if raw is None:
        return default
    return raw.strip().lower() in ("1", "true", "yes", "on")


# SECURITY WARNING: keep the secret key used in production secret!
# Read from the environment in production. The hardcoded fallback is only for
# local development convenience and is intentionally prefixed `django-insecure-`.
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-qfjbcse1zmp=6y84(^#btvgjyi#hv@7wqz81op*#89x+o*0)bi",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool("DEBUG", default=True)

# Comma-separated list of hosts allowed to serve the site.
# Vercel/Render style: pass `ALLOWED_HOSTS=example.com,www.example.com`.
# Render injects RENDER_EXTERNAL_HOSTNAME automatically; Vercel injects VERCEL_URL.
_allowed_hosts_env = os.environ.get(
    "ALLOWED_HOSTS",
    "localhost,127.0.0.1,0.0.0.0",
)
ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_env.split(",") if h.strip()]

for _host_env in ("RENDER_EXTERNAL_HOSTNAME", "VERCEL_URL"):
    _h = os.environ.get(_host_env)
    if _h and _h not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(_h)

# Allow `*` only when explicitly opted in (e.g. behind a trusted proxy).
if os.environ.get("ALLOWED_HOSTS_WILDCARD") == "1":
    ALLOWED_HOSTS = ["*"]

# Trust the proxy's HTTPS termination so request.is_secure() returns True
# behind Render / Vercel / typical reverse proxies.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# CSRF trusted origins for HTTPS deployments. Read a comma-separated list
# from the env, then auto-append the platform-provided hostnames.
_csrf_trusted = os.environ.get("CSRF_TRUSTED_ORIGINS", "")
CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf_trusted.split(",") if o.strip()]
for _host_env in ("RENDER_EXTERNAL_HOSTNAME", "VERCEL_URL"):
    _h = os.environ.get(_host_env)
    if _h:
        origin = f"https://{_h}"
        if origin not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(origin)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'authentication',
    'chat',
    'profile_app',  
    
    # Third-party apps
    'channels',
   # 'drf_spectacular',
]


INSTALLED_APPS += ['drf_spectacular']
INSTALLED_APPS += ['django_filters']

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',  # Default JSON response
        'rest_framework.renderers.BrowsableAPIRenderer',  # Browsable API
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend'
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',

    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ),
    
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Portfolio API',
    'DESCRIPTION': 'Dynamic Developer Portfolio with Telegram Integration',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
}
ASGI_APPLICATION = 'portfolio_project.asgi.application'


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'csp.middleware.CSPMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CSP_DEFAULT_SRC = ["'self'"]
CSP_SCRIPT_SRC = ["'self'", "'unsafe-inline'"]
CSP_STYLE_SRC = ["'self'", "'unsafe-inline'"]

ROOT_URLCONF = 'portfolio_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'portfolio_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
'''
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
'''

import os
from dotenv import load_dotenv
from urllib.parse import urlparse

load_dotenv()

# Database configuration
# ----------------------
# When `DATABASE_URL` is set we use Postgres (production / staging behavior).
# When it isn't, we fall back to a local sqlite file so the project is
# trivially runnable for development and testing.
_database_url = os.getenv("DATABASE_URL")

if _database_url:
    _parsed = urlparse(_database_url)
    _name = _parsed.path or ''
    if isinstance(_name, bytes):
        _name = _name.decode('utf-8')
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': _name.lstrip('/'),
            'USER': _parsed.username or '',
            'PASSWORD': _parsed.password or '',
            'HOST': _parsed.hostname or '',
            'PORT': _parsed.port or 5432,
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# settings.py
LOGIN_URL = '/login/' 


LOGIN_REDIRECT_URL = '/'  # Redirect to the homepage after login
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# WhiteNoise: hashed + compressed static files in production.
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

AUTH_USER_MODEL = 'authentication.PortfolioUser'

# Security headers — only enforce HTTPS-only cookies + HSTS in production.
# In development (DEBUG=True) we relax these so http://localhost works.
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_HSTS_SECONDS = 0 if DEBUG else 31536000
SECURE_CONTENT_TYPE_NOSNIFF = True
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
