# Generated by Django 5.2 on 2025-04-20 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('avatar', models.URLField(max_length=500)),
                ('bio', models.TextField(max_length=2000)),
                ('tagline', models.CharField(max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interactive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_playground_enabled', models.BooleanField(default=False)),
                ('live_streaming', models.BooleanField(default=False)),
                ('last_stream_start', models.DateTimeField(null=True)),
                ('active_challenges', models.JSONField(default=list)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profile_app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_type', models.CharField(choices=[('PRO', 'Professional'), ('EDU', 'Education'), ('CERT', 'Certification'), ('ACHV', 'Achievement')], max_length=4)),
                ('title', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='profile_app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('BLOG', 'Blog Post'), ('WRITE', 'Technical Writing'), ('VIDEO', 'Video Demo'), ('DECK', 'Presentation')], max_length=5)),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('published_date', models.DateField()),
                ('description', models.TextField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='profile_app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('project_url', models.URLField()),
                ('repo_url', models.URLField(blank=True)),
                ('tech_stack', models.JSONField()),
                ('project_type', models.CharField(choices=[('LIVE', 'Live Project'), ('ARCH', 'Archived'), ('EXPR', 'Experiment'), ('OS', 'Open Source')], max_length=4)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='profile_app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('proficiency', models.IntegerField(default=50)),
                ('skill_type', models.CharField(choices=[('TECH', 'Technical'), ('TOOL', 'Tool'), ('SOFT', 'Soft Skill'), ('LANG', 'Language')], max_length=4)),
                ('category', models.CharField(max_length=50)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='profile_app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('GH', 'GitHub'), ('LI', 'LinkedIn'), ('TW', 'Twitter'), ('TG', 'Telegram')], max_length=2)),
                ('url', models.URLField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='profile_app.profile')),
            ],
        ),
    ]
